//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Comments")
export class CommentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Content: string;

@Column({nullable: true})
Author: string;

@Column({nullable: true})
Task: string;

@Column({nullable: true})
Timestamp: string;


}
