//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Projects")
export class ProjectsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Title: string;

@Column({nullable: true})
Description: string;

@Column({nullable: true})
Deadline: string;

@Column({nullable: true})
AssignedTasks: string;


}
