//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Users")
export class UsersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Name: string;

@Column({nullable: true})
Email: string;

@Column({nullable: true})
TasksAssigned: string;

@Column({nullable: true})
Role: string;


}
